name: Release Automation
 
on:
  push:
    tags:
      - v*
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Bun
      uses: bun-lang/setup-bun@v1
      with:
        version: '1'
 
    - name: Generate Documentation
      run: |
        bun run ./generatort.ts
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
 
      - name: Create Release Notes
        id: create_release_notes
        run: |
          echo "Generating release notes..."
        shell: bash
 
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: output.txt
