name: Release Automation
 
on:
  push:
    tags:
      - v*
 
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run ./generator.ts
      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: output file
          path: output.txt
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
 
      - name: Create Release Notes
        id: create_release_notes
        run: |
          echo "Generating release notes..."
        shell: bash

      - name: Download output file
        uses: actions/download-artifact@v4
        with:
          name: output.txt
 
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: output.txt
